import { NextResponse } from "next/server";
import  PDFDocument  from "pdfkit";

import { getActors } from "@/lib/db/queries";

export async function GET() {
  const actors = await getActors();

  const doc = new PDFDocument({
    size: "A4",
    margin: 50,
  });

  const chunks: Buffer[] = [];

  doc.on("data", (chunk: Buffer) => {
    chunks.push(chunk);
  });

  const pdfReady = new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => {
      resolve(Buffer.concat(chunks));
    });

    doc.on("error", reject);
  });

  doc.info.Title = "Dark Web Threat Intelligence Report";
  doc.info.Author = "Dark Web Intelligence Platform";

  doc
    .fontSize(22)
    .font("Helvetica-Bold")
    .text("Dark Web Threat Intelligence Report");

  doc.moveDown();

  doc
    .fontSize(11)
    .font("Helvetica")
    .text(
      "Synthetic demonstration report generated by the Dark Web Threat Intelligence Platform."
    );

  doc.moveDown();

  doc
    .fontSize(16)
    .font("Helvetica-Bold")
    .text("Actor Intelligence");

  doc.moveDown(0.5);

  for (const actor of actors) {
    doc
      .fontSize(12)
      .font("Helvetica-Bold")
      .text(actor.name);

    doc
      .fontSize(10)
      .font("Helvetica")
      .text(`Status: ${actor.status}`)
      .text(
        `Attribution Confidence: ${actor.attributionConfidence}%`
      )
      .text(
        `First Seen: ${actor.firstSeen.toISOString().split("T")[0]}`
      )
      .text(
        `Last Seen: ${actor.lastSeen.toISOString().split("T")[0]}`
      );

    doc.moveDown();

    doc
      .fontSize(10)
      .text(actor.summary);

    doc.moveDown();
  }

  doc.end();

  const pdfBuffer = await pdfReady;

  return new NextResponse(pdfBuffer as BodyInit, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition":
        "attachment; filename=threat-intelligence-report.pdf",
    },
  });
}